name: mustafa
personal_access_token: 5sat9MtD6VhstvsAHLxy
# repo_url: https://rnd-gitlab-eu.huawei.com/htrdc-isd/ebg/CCOMS
repo_url: https://rnd-gitlab-eu.huawei.com/
#https://rnd-gitlab-eu.huawei.com/users/sign_in